AWSTemplateFormatVersion: 2010-09-09
Resources:
  Haversine:
    Properties:
      CodeUri: s3://lambdascideploy/b7ecedd117bfa7fd5c726be6c2f88ad7
      Events:
        PostEvent:
          Properties:
            Method: post
            Path: /haversine
          Type: Api
      Handler: haversine.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
  HaversineApiHelp:
    Properties:
      CodeUri: s3://lambdascideploy/b7ecedd117bfa7fd5c726be6c2f88ad7
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /haversine/api
          Type: Api
      Handler: haversine.apihelphandler
      Runtime: python3.6
    Type: AWS::Serverless::Function
  HelloWorld:
    Properties:
      CodeUri: s3://lambdascideploy/b7ecedd117bfa7fd5c726be6c2f88ad7
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /
          Type: Api
      Handler: index.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
  LinearInterpolation:
    Properties:
      CodeUri: s3://lambdascideploy/e983a61b988439e4b7a6244ef2e8420d
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /interpolation/linear
          Type: Api
      Handler: interpolation.linearHandler
      Runtime: python3.6
    Type: AWS::Serverless::Function
  LinearInterpolationApi:
    Properties:
      CodeUri: s3://lambdascideploy/e983a61b988439e4b7a6244ef2e8420d
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /interpolation/linear/api
          Type: Api
      Handler: interpolation.linearApiHelp
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform:
- AWS::Serverless-2016-10-31
