AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            
  Haversine:
    Type: AWS::Serverless::Function
    Properties:
      Handler: haversine.handler
      Runtime: python3.6
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /haversine
            Method: post
  HaversineApiHelp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: haversine.apihelphandler
      Runtime: python3.6
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /haversine/api
            Method: get
  
